feature: support two mode when abort:  `cancel`/`abort`
Flared/dramatiq-abort pull request #4
Opened 2021-03-21 16:25 UTC by JetDrag

`Cancel` to abort the pending task, and the default `abort` to abort the pending or running task.

 `Cancel`  mode won't kill the running task to reduce the undetermined status in worker thread.

2021-03-22 16:26 UTC, isra17 requested changes
I like the idea, I would be interested to merge after a few changes.

Few comments:

I just updated the CI workflow, I think it should now run on incoming PR. You can rebase on master and ensure the test suite works and the code is properly formatted: https://github.com/Flared/dramatiq-abort/blob/master/CONTRIBUTING.md

2021-03-22 16:26 UTC, isra17 commented on src/dramatiq_abort/backends/redis.py
> +    def notify_many(self, keys: List[bytes], ttl: int) -> None:
nit: `List` can be `Iterable`

2021-03-22 16:26 UTC, isra17 commented on src/dramatiq_abort/backends/redis.py
> +    def notify_many(self, keys: List[bytes], ttl: int) -> None:
You could also rewrite `notify` to simply call `self.notify_many([key], ttl)`. This would avoid having duplicate implementation.

2021-03-22 16:26 UTC, isra17 commented on src/dramatiq_abort/middleware.py
> +def abort(message_id: str, middleware: Optional[Abortable] = None, mode='abort') -> None:
`mode` should be a keyword only argument, be an `enum.Enum` and typed:

```python
def abort(message_id: str, middleware: Optional[Abortable] = None, *, mode: AbortMode=AbortMode.Abort) -> None:
```

2021-03-22 16:26 UTC, isra17 commented on tests/test_abortable.py
> +    if mode == 'abort':
Make separate test and drop the `mode` fixture.

There's no point using parameters fixtures if we end up doing a bunch of `if` inside the test.

2021-03-25 17:24 UTC, JetDrag commented
@isra17 Hi, I've improved the PR code according the developer guide and the review. The tox task also successed.

2021-04-07 13:49 UTC, isra17 commented
The diff is all mangled with commit from master.

If you can sqash all your change into one commit this would make the code cleaner and reviewable.

A simple `git reset Flared/master && git commit` should do it. 

Thanks

2021-04-23 15:22 UTC, closed without merging